-- MySQL Script
-- 2021-07-29 12:36
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `luigi2_test` ;

-- >>LG2-267
ALTER TABLE `luigi2_test`.`authorities` 
ADD COLUMN `api_yn` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'API/画面制御' AFTER `function_id`,
CHANGE COLUMN `role_id` `role_id` VARCHAR(8) NOT NULL COMMENT 'ロールID' ,
CHANGE COLUMN `function_id` `function_id` VARCHAR(12) NOT NULL COMMENT '機能ID' ,
ADD INDEX `CAND_authorities` (`tenant_id` ASC, `role_id` ASC, `function_id` ASC);
-- <<LG2-267

-- >>LG2-LG2-265
ALTER TABLE `luigi2_test`.`users` 
DROP COLUMN `remember_token`,
DROP COLUMN `password`,
ADD COLUMN `sub` VARCHAR(128) NULL DEFAULT NULL COMMENT 'UUID' AFTER `active`;
-- <<LG2-LG2-265

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
