-- MySQL Script
-- 2021-08-02 18:33
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- >>LG2-293
ALTER TABLE `maintenance_requests_customer_individual` 
CHANGE COLUMN `customer_id` `customer_id` VARCHAR(12) NULL DEFAULT NULL COMMENT '顧客ID' ;

ALTER TABLE `maintenance_requests_customer_corporate` 
CHANGE COLUMN `customer_id` `customer_id` VARCHAR(12) NULL DEFAULT NULL COMMENT '顧客ID' ;
-- <<LG2-293


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
