-- MySQL Script
-- 2021-09-03 21:06
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



ALTER TABLE `beneficiaries` 
DROP COLUMN `addr_knj_2`,
DROP COLUMN `addr_knj_1`,
DROP COLUMN `addr_knj_pref`,
DROP COLUMN `addr_zip_code`,
DROP COLUMN `date_of_birth`,
DROP COLUMN `sex`;

ALTER TABLE `maintenance_requests_beneficiaries` 
DROP COLUMN `addr_knj_2`,
DROP COLUMN `addr_knj_1`,
DROP COLUMN `addr_knj_pref`,
DROP COLUMN `addr_zip_code`,
DROP COLUMN `date_of_birth`,
DROP COLUMN `sex`;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
