-- MySQL Script
-- 2022-08-24 08:32
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


ALTER TABLE `sales_premiums` 
DROP COLUMN `frequency`;

ALTER TABLE `sales_products` 
DROP COLUMN `continue_policy_reclaim_flag`,
DROP COLUMN `first_policy_reclaim_flag`,
ADD COLUMN `premium` INT(8) UNSIGNED NULL DEFAULT NULL COMMENT '保険料' AFTER `issue_age_lower`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
