-- MySQL Script
-- 2021-08-17 16:24
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


ALTER TABLE `beneficiaries` 
ADD COLUMN `beneficiary_code` VARCHAR(12) NULL DEFAULT NULL COMMENT '受取人ID' AFTER `tenant_id`;

ALTER TABLE `maintenance_requests_customer` 
ADD COLUMN `beneficiary_code` VARCHAR(12) NULL DEFAULT NULL COMMENT '受取人ID' AFTER `role`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
