-- MySQL Script
-- 2022-10-07 11:51
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



ALTER TABLE `agencies` 
CHANGE COLUMN `corporate_number` `corporate_number` CHAR(13) NULL DEFAULT NULL COMMENT '法人番号' ;

ALTER TABLE `maintenance_requests_customer_individual` 
DROP COLUMN `business_name_knj`,
DROP COLUMN `business_name_kana`;

ALTER TABLE `maintenance_requests_customer_corporate` 
DROP COLUMN `corp_number`;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
