-- MySQL Script
-- 2022-10-07 12:41
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



ALTER TABLE `agencies` 
CHANGE COLUMN `rep10e_tel` `rep10e_tel` VARCHAR(13) NULL DEFAULT NULL COMMENT '代表電話番号' ,
CHANGE COLUMN `person_in_charge_tel` `person_in_charge_tel` VARCHAR(13) NULL DEFAULT NULL COMMENT '担当者電話番号' ;

ALTER TABLE `agency_branches` 
CHANGE COLUMN `agency_branch_tel_no` `agency_branch_tel_no` VARCHAR(13) NULL DEFAULT NULL COMMENT '支店電話番号' ,
CHANGE COLUMN `person_in_charge_tel` `person_in_charge_tel` VARCHAR(13) NULL DEFAULT NULL COMMENT '担当者電話番号' ;

ALTER TABLE `third_party_org` 
CHANGE COLUMN `org_tel` `org_tel` VARCHAR(15) NULL DEFAULT NULL COMMENT '第三者機関連絡先電話番号' ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
