-- MySQL Script
-- 2022-08-24 08:31
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


ALTER TABLE `sales_premiums` 
ADD COLUMN `frequency` VARCHAR(2) NULL DEFAULT NULL COMMENT '保険料払込回数' AFTER `premium`;

ALTER TABLE `sales_products` 
DROP COLUMN `premium`,
ADD COLUMN `first_policy_reclaim_flag` CHAR(1) NULL DEFAULT NULL COMMENT '初回保険併徴・再請求フラグ' AFTER `rounding_type`,
ADD COLUMN `continue_policy_reclaim_flag` CHAR(1) NULL DEFAULT NULL COMMENT '継続保険併徴・再請求フラグ' AFTER `first_policy_reclaim_flag`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
