-- MySQL Script
-- 2021-11-02 12:30
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



ALTER TABLE `claim_headers` 
DROP COLUMN `claimant_address`,
ADD COLUMN `claimant_addr_zip_code` VARCHAR(8) NULL DEFAULT NULL COMMENT '請求者郵便番号' AFTER `claimant_date_of_birth`,
ADD COLUMN `claimant_addr_knj_pref` TEXT NULL DEFAULT NULL COMMENT '請求者住所―県(漢字)' AFTER `claimant_addr_zip_code`,
ADD COLUMN `claimant_addr_knj_1` TEXT NULL DEFAULT NULL COMMENT '請求者住所1(漢字)' AFTER `claimant_addr_knj_pref`,
ADD COLUMN `claimant_addr_knj_2` TEXT NULL DEFAULT NULL COMMENT '請求者住所2(漢字)' AFTER `claimant_addr_knj_1`;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
