-- MySQL Script
-- 2021-10-13 5:03
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



ALTER TABLE `sales_products` 
ADD COLUMN `surrender_charge_rate` DECIMAL(4,3) UNSIGNED NULL DEFAULT NULL COMMENT '解約控除割合' AFTER `contract_underwriting_waivers`,
ADD COLUMN `min_surrender_charge` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '最低解約控除額' AFTER `surrender_charge_rate`,
ADD COLUMN `max_surrender_charge` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '最高解約控除額' AFTER `min_surrender_charge`,
ADD COLUMN `rounding_type` CHAR(1) NULL DEFAULT NULL COMMENT '端数処理タイプ' AFTER `max_surrender_charge`;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
