-- MySQL Script
-- 2021-09-13 14:53
--

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



ALTER TABLE `agencies` 
DROP COLUMN `agency_status`,
DROP COLUMN `mg_kana_mei`,
DROP COLUMN `mg_kana_sei`,
DROP COLUMN `mg_knj_mei`,
DROP COLUMN `mg_knj_sei`,
DROP COLUMN `em_kana_mei`,
DROP COLUMN `em_kana_sei`,
DROP COLUMN `em_knj_mei`,
DROP COLUMN `em_knj_sei`,
DROP COLUMN `rep_date_of_birth`,
CHANGE COLUMN `rep_tel` `rep10e_tel` VARCHAR(13) NULL DEFAULT NULL COMMENT '代表電話番号' ,
CHANGE COLUMN `rep_name_knj_sei` `rep10e_name_knj_sei` TEXT NULL DEFAULT NULL COMMENT '代表者姓(漢字)' ,
CHANGE COLUMN `rep_name_knj_mei` `rep10e_name_knj_mei` TEXT NULL DEFAULT NULL COMMENT '代表者名(漢字)' ,
CHANGE COLUMN `rep_name_kana_sei` `rep10e_name_kana_sei` TEXT NULL DEFAULT NULL COMMENT '代表者姓(カナ)' ,
CHANGE COLUMN `rep_name_kana_mei` `rep10e_name_kana_mei` TEXT NULL DEFAULT NULL COMMENT '代表者名(カナ)' ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
